fix: deploy pipeline run system healthcheck

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -197,53 +197,53 @@ jobs:
       run: |
         URL=$BACKOFFICE_API_URL/v1/system/healthcheck
 
-        # aws configure set default.aws_access_key_id $ACCESS_KEY_ID
-        # aws configure set default.aws_secret_access_key $SECRET_ACCESS_KEY_ID
-        # aws configure set default.region $REGION
-        # aws configure set default.role_session_name "Pipeline"
+        aws configure set default.aws_access_key_id $ACCESS_KEY_ID
+        aws configure set default.aws_secret_access_key $SECRET_ACCESS_KEY_ID
+        aws configure set default.region $REGION
+        aws configure set default.role_session_name "Pipeline"
 
-        # aws configure set region $REGION --profile cross-account
-        # aws configure set role_arn arn:aws:iam::$ACCOUNT_ID:role/bastion-ssm-send-command --profile cross-account
-        # aws configure set source_profile default --profile cross-account
+        aws configure set region $REGION --profile cross-account
+        aws configure set role_arn arn:aws:iam::$ACCOUNT_ID:role/bastion-ssm-send-command --profile cross-account
+        aws configure set source_profile default --profile cross-account
 
-        # echo $URL
-        # COMMAND_ID=$(aws ssm send-command --profile cross-account --instance-id $INSTANCE_ID --document-name AWS-RunShellScript --parameters "{\"commands\":[\"#!/bin/bash\",\"curl -X POST $URL -H 'x-api-key: $ROAD_API_KEY' --fail\"]}" --query 'Command.CommandId' --output text)
+        echo $URL
+        COMMAND_ID=$(aws ssm send-command --profile cross-account --instance-id $INSTANCE_ID --document-name AWS-RunShellScript --parameters "{\"commands\":[\"#!/bin/bash\",\"curl -X POST $URL -H 'x-api-key: $ROAD_API_KEY' --fail\"]}" --query 'Command.CommandId' --output text)
 
-        # for i in {1..120}
-        # do
-        #   status=$(aws ssm get-command-invocation --profile cross-account --instance-id $INSTANCE_ID --command-id $COMMAND_ID --query 'Status' --output text)
+        for i in {1..120}
+        do
+          status=$(aws ssm get-command-invocation --profile cross-account --instance-id $INSTANCE_ID --command-id $COMMAND_ID --query 'Status' --output text)
 
-        #   if [[ "$status" == "Failed" ]]; then
-        #     exit 1
-        #   fi
+          if [[ "$status" == "Failed" ]]; then
+            exit 1
+          fi
 
-        #   echo $status
-        #   if [[ "$status" == "Success" ]]; then
-        #     break
-        #   fi
+          echo $status
+          if [[ "$status" == "Success" ]]; then
+            break
+          fi
 
-        #   sleep 1
-        # done
+          sleep 1
+        done
 
-        # if [[ "$status" == "InProgress" ]]; then
-        #   echo "Timed out"
-        #   exit 1
-        # fi
+        if [[ "$status" == "InProgress" ]]; then
+          echo "Timed out"
+          exit 1
+        fi
 
-        # response=$(aws ssm get-command-invocation --profile cross-account --instance-id $INSTANCE_ID --command-id $COMMAND_ID --query 'StandardOutputContent' --output text)
-        # echo "$response"
+        response=$(aws ssm get-command-invocation --profile cross-account --instance-id $INSTANCE_ID --command-id $COMMAND_ID --query 'StandardOutputContent' --output text)
+        echo "$response"
 
-        # if echo "$response" | grep -q "unhealthy"; then
-        #   echo "System is unhealthy"
-        #   exit 1
-        # fi
+        if echo "$response" | grep -q "unhealthy"; then
+          echo "System is unhealthy"
+          exit 1
+        fi
 
-        # if echo "$response" | grep -q "healthy"; then
-        #   echo "System is healthy"
-        #   exit 0
-        # fi
+        if echo "$response" | grep -q "healthy"; then
+          echo "System is healthy"
+          exit 0
+        fi
 
-        # exit 1
+        exit 1
       shell: bash
       env:
         ACCESS_KEY_ID: ${{ secrets.VBR_AWS_ACCESS_KEY_ID_DEVOPS }}
